# Generated by Django 6.0.5 on 2026-05-28 11:18

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employees', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Grievance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('category', models.CharField(choices=[('workplace', 'Workplace Environment'), ('payroll', 'Payroll & Compensation'), ('harassment', 'Harassment or Bullying'), ('management', 'Management & Leadership'), ('policy', 'Policy & Benefits'), ('other', 'Other Grievance')], default='other', max_length=30)),
                ('description', models.TextField()),
                ('status', models.CharField(choices=[('pending', 'Pending Review'), ('in_progress', 'Under Investigation'), ('resolved', 'Resolved'), ('escalated', 'Escalated'), ('closed', 'Closed')], default='pending', max_length=20)),
                ('resolution_details', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('resolved_at', models.DateTimeField(blank=True, null=True)),
                ('assigned_to', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='resolved_grievances', to=settings.AUTH_USER_MODEL)),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='raised_grievances', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'grievances',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['employee', 'status'], name='grievances_employe_f98cd3_idx'), models.Index(fields=['category'], name='grievances_categor_1fd0d2_idx')],
            },
        ),
    ]
