# Generated by Django 6.0.5 on 2026-05-27 05:21

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AnalyticsSnapshot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('snapshot_date', models.DateField(db_index=True, unique=True)),
                ('total_employees', models.IntegerField()),
                ('active_employees', models.IntegerField()),
                ('on_leave_employees', models.IntegerField()),
                ('exited_employees_ytd', models.IntegerField()),
                ('attrition_rate', models.DecimalField(decimal_places=2, max_digits=5)),
                ('open_positions', models.IntegerField()),
                ('applications_pending', models.IntegerField()),
                ('offers_pending', models.IntegerField()),
                ('total_payroll_amount', models.DecimalField(decimal_places=2, max_digits=15)),
                ('processed_payrolls', models.IntegerField()),
                ('pending_payrolls', models.IntegerField()),
                ('average_attendance_rate', models.DecimalField(decimal_places=2, max_digits=5)),
                ('absent_today', models.IntegerField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'analytics_snapshots',
                'ordering': ['-snapshot_date'],
            },
        ),
        migrations.CreateModel(
            name='DepartmentAnalytics',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('department_name', models.CharField(max_length=100)),
                ('snapshot_date', models.DateField()),
                ('employee_count', models.IntegerField()),
                ('average_salary', models.DecimalField(decimal_places=2, max_digits=12)),
                ('attrition_rate', models.DecimalField(decimal_places=2, max_digits=5)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'department_analytics',
                'ordering': ['-snapshot_date'],
                'unique_together': {('department_name', 'snapshot_date')},
            },
        ),
    ]
