# Generated by Django 6.0.5 on 2026-05-28 14:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('analytics', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='HRReport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('scope', models.CharField(choices=[('department', 'Department'), ('grade', 'Grade'), ('period', 'Period'), ('cost_centre', 'Cost Centre')], max_length=50)),
                ('metrics', models.JSONField(blank=True, default=dict)),
                ('generated_date', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'hr_reports',
                'ordering': ['-generated_date'],
            },
        ),
    ]
