# Generated by Django 6.0.5 on 2026-05-28 14:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notifications', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notification',
            name='notification_type',
            field=models.CharField(choices=[('leave_status', 'Leave Status'), ('leave_reminder', 'Leave Reminder'), ('payroll', 'Payroll Alert'), ('recruitment', 'Recruitment Update'), ('appraisal', 'Appraisal Reminder'), ('attendance', 'Attendance Alert'), ('system', 'System Message'), ('leave', 'Leave'), ('payroll_alert', 'Payroll'), ('appraisal_alert', 'Appraisal'), ('recruitment_alert', 'Recruitment'), ('compliance', 'Compliance')], max_length=50),
        ),
    ]
