# Generated by Django 6.0.5 on 2026-05-27 05:21

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='DashboardCard',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('card_type', models.CharField(choices=[('metric', 'Metric Card'), ('chart', 'Chart Card'), ('list', 'List Card'), ('summary', 'Summary Card')], max_length=20)),
                ('applicable_role', models.CharField(choices=[('employee', 'Employee'), ('manager', 'Manager'), ('hrbp', 'HR Business Partner'), ('recruiter', 'Recruiter'), ('payroll', 'Payroll Executive'), ('hr_admin', 'HR Admin'), ('super_admin', 'Super Admin')], max_length=50)),
                ('description', models.TextField(blank=True, null=True)),
                ('icon', models.CharField(blank=True, max_length=50, null=True)),
                ('position', models.IntegerField(default=0)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'db_table': 'dashboard_cards',
                'ordering': ['applicable_role', 'position'],
            },
        ),
    ]
