# Generated by Django 6.0.5 on 2026-05-27 10:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dashboardcard',
            name='applicable_role',
            field=models.CharField(choices=[('employee', 'Employee'), ('manager', 'Manager'), ('hr', 'HR (Human Resources)'), ('recruiter', 'Recruiter'), ('payroll', 'Payroll Executive'), ('admin', 'Admin')], max_length=50),
        ),
    ]
