# Generated by Django 6.0.5 on 2026-05-28 14:06

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employees', '0003_department_cost_centre_code_department_hrbp_user_and_more'),
        ('recruitment', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='candidate',
            name='source_channel',
            field=models.CharField(choices=[('portal', 'Portal'), ('referral', 'Referral'), ('agency', 'Agency'), ('campus', 'Campus')], default='portal', max_length=20),
        ),
        migrations.AddField(
            model_name='interviewround',
            name='outcome',
            field=models.CharField(choices=[('pass', 'Pass'), ('fail', 'Fail'), ('hold', 'Hold'), ('pending', 'Pending')], default='pending', max_length=20),
        ),
        migrations.AddField(
            model_name='interviewround',
            name='requisition',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='interview_rounds', to='recruitment.jobrequisition'),
        ),
        migrations.AddField(
            model_name='jobrequisition',
            name='department_ref',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='requisitions', to='employees.department'),
        ),
        migrations.AddField(
            model_name='jobrequisition',
            name='designation_ref',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='requisitions', to='employees.designation'),
        ),
        migrations.AddField(
            model_name='jobrequisition',
            name='grade',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='requisitions', to='employees.gradestructure'),
        ),
        migrations.AddField(
            model_name='jobrequisition',
            name='required_by',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='offerletter',
            name='issued_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='offerletter',
            name='joining_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='offerletter',
            name='requisition',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='offer_letters', to='recruitment.jobrequisition'),
        ),
        migrations.AlterField(
            model_name='jobrequisition',
            name='department',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='jobrequisition',
            name='designation',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='jobrequisition',
            name='status',
            field=models.CharField(choices=[('draft', 'Draft'), ('approved', 'Approved'), ('open', 'Open'), ('filled', 'Filled'), ('cancelled', 'Cancelled')], default='draft', max_length=20),
        ),
        migrations.AlterField(
            model_name='offerletter',
            name='status',
            field=models.CharField(choices=[('issued', 'Issued'), ('accepted', 'Accepted'), ('declined', 'Declined'), ('revoked', 'Revoked'), ('draft', 'Draft')], default='draft', max_length=20),
        ),
    ]
