# Generated by Django 6.0.5 on 2026-05-29 17:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recruitment', '0003_candidateaccount_candidate_candidate_account'),
    ]

    operations = [
        migrations.AddField(
            model_name='candidateaccount',
            name='backlogs',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
        migrations.AddField(
            model_name='candidateaccount',
            name='education_details',
            field=models.TextField(blank=True, null=True),
        ),
    ]
