# Generated by Django 6.0.5 on 2026-05-29 17:31

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recruitment', '0004_candidateaccount_backlogs_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='InterviewChatMessage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sender_type', models.CharField(max_length=20)),
                ('sender_name', models.CharField(max_length=200)),
                ('message', models.TextField()),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('interview_round', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='chat_messages', to='recruitment.interviewround')),
            ],
            options={
                'db_table': 'interview_chat_messages',
                'ordering': ['timestamp'],
            },
        ),
    ]
