# Generated by Django 6.0.5 on 2026-05-29 18:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recruitment', '0005_interviewchatmessage'),
    ]

    operations = [
        migrations.AlterField(
            model_name='candidate',
            name='status',
            field=models.CharField(choices=[('applied', 'Applied'), ('shortlisted', 'Shortlisted'), ('interview_scheduled', 'Interview Scheduled'), ('selected', 'Selected'), ('offered', 'Offer Released'), ('offer_accepted', 'Offer Letter Accepted'), ('background_verification', 'Background Verification'), ('joining_confirmed', 'Joining Date Confirmed'), ('joined', 'Joined Company'), ('onboarded', 'HR Onboarded / Employee Access Active'), ('rejected', 'Rejected')], default='applied', max_length=30),
        ),
    ]
