# Generated by Django 6.0.5 on 2026-05-29 21:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recruitment', '0006_expand_candidate_status_choices'),
    ]

    operations = [
        migrations.AddField(
            model_name='candidateaccount',
            name='cgpa',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=4, null=True),
        ),
        migrations.AddField(
            model_name='candidateaccount',
            name='college',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='candidateaccount',
            name='inter_percentage',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True),
        ),
        migrations.AddField(
            model_name='candidateaccount',
            name='preferred_locations',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='candidateaccount',
            name='tenth_percentage',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True),
        ),
    ]
