# Generated by Django 6.0.5 on 2026-05-27 05:21

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AppraisalCycle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('description', models.TextField(blank=True, null=True)),
                ('start_date', models.DateField()),
                ('end_date', models.DateField()),
                ('status', models.CharField(choices=[('planning', 'Planning'), ('active', 'Active'), ('completed', 'Completed'), ('archived', 'Archived')], default='planning', max_length=20)),
                ('financial_year', models.CharField(max_length=9)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='appraisal_cycles_created', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'appraisal_cycles',
                'ordering': ['-start_date'],
            },
        ),
        migrations.CreateModel(
            name='GoalSheet',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('goal_title', models.CharField(max_length=200)),
                ('goal_description', models.TextField()),
                ('target_value', models.CharField(max_length=100)),
                ('weight', models.IntegerField(default=10)),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('submitted', 'Submitted'), ('approved', 'Approved'), ('in_progress', 'In Progress'), ('completed', 'Completed')], default='draft', max_length=20)),
                ('manager_comments', models.TextField(blank=True, null=True)),
                ('actual_value', models.CharField(blank=True, max_length=100, null=True)),
                ('achievement_percentage', models.IntegerField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('appraisal_cycle', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='goal_sheets', to='appraisal.appraisalcycle')),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='goal_sheets', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'goal_sheets',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='PromotionRecommendation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('current_designation', models.CharField(max_length=100)),
                ('recommended_designation', models.CharField(max_length=100)),
                ('reason', models.TextField()),
                ('status', models.CharField(choices=[('recommended', 'Recommended'), ('approved', 'Approved'), ('rejected', 'Rejected'), ('implemented', 'Implemented')], default='recommended', max_length=20)),
                ('salary_increment_percentage', models.DecimalField(decimal_places=2, default=0, max_digits=5)),
                ('effective_date', models.DateField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('appraisal_cycle', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='promotion_recommendations', to='appraisal.appraisalcycle')),
                ('approved_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='promotions_approved', to=settings.AUTH_USER_MODEL)),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='promotion_recommendations', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'promotion_recommendations',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='EmployeeAppraisal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('self_review', 'Self Review'), ('manager_review', 'Manager Review'), ('final', 'Final'), ('completed', 'Completed')], default='draft', max_length=20)),
                ('self_rating', models.IntegerField(blank=True, choices=[(1, 'Poor'), (2, 'Below Average'), (3, 'Average'), (4, 'Good'), (5, 'Excellent')], null=True)),
                ('self_comments', models.TextField(blank=True, null=True)),
                ('manager_rating', models.IntegerField(blank=True, choices=[(1, 'Poor'), (2, 'Below Average'), (3, 'Average'), (4, 'Good'), (5, 'Excellent')], null=True)),
                ('manager_comments', models.TextField(blank=True, null=True)),
                ('final_rating', models.IntegerField(blank=True, choices=[(1, 'Poor'), (2, 'Below Average'), (3, 'Average'), (4, 'Good'), (5, 'Excellent')], null=True)),
                ('performance_remarks', models.TextField(blank=True, null=True)),
                ('strengths', models.TextField(blank=True, null=True)),
                ('areas_for_improvement', models.TextField(blank=True, null=True)),
                ('development_plan', models.TextField(blank=True, null=True)),
                ('submitted_at', models.DateTimeField(blank=True, null=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('appraisal_cycle', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='employee_appraisals', to='appraisal.appraisalcycle')),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='appraisals', to=settings.AUTH_USER_MODEL)),
                ('manager', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='appraisals_given', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'employee_appraisals',
                'ordering': ['-created_at'],
                'unique_together': {('appraisal_cycle', 'employee')},
            },
        ),
    ]
