# Generated by Django 6.0.5 on 2026-05-28 14:03

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appraisal', '0001_initial'),
        ('employees', '0003_department_cost_centre_code_department_hrbp_user_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='appraisalcycle',
            name='cycle_type',
            field=models.CharField(choices=[('mid_year', 'Mid-Year'), ('annual', 'Annual')], default='annual', max_length=20),
        ),
        migrations.AddField(
            model_name='appraisalcycle',
            name='goal_setting_end',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='appraisalcycle',
            name='goal_setting_start',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='appraisalcycle',
            name='review_end',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='appraisalcycle',
            name='review_start',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='appraisalcycle',
            name='year',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='goalsheet',
            name='final_rating',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='goalsheet',
            name='goals_json',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name='goalsheet',
            name='manager',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='goal_sheets_managed', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='goalsheet',
            name='manager_rating',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='goalsheet',
            name='self_rating',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='promotionrecommendation',
            name='current_grade',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='promotions_current', to='employees.gradestructure'),
        ),
        migrations.AddField(
            model_name='promotionrecommendation',
            name='recommended_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='promotions_recommended_by', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='promotionrecommendation',
            name='recommended_grade',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='promotions_recommended', to='employees.gradestructure'),
        ),
        migrations.AlterField(
            model_name='appraisalcycle',
            name='status',
            field=models.CharField(choices=[('planning', 'Planning'), ('active', 'Active'), ('completed', 'Completed'), ('archived', 'Archived'), ('upcoming', 'Upcoming'), ('closed', 'Closed')], default='planning', max_length=20),
        ),
        migrations.AlterField(
            model_name='goalsheet',
            name='goal_description',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='goalsheet',
            name='goal_title',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='goalsheet',
            name='status',
            field=models.CharField(choices=[('draft', 'Draft'), ('submitted', 'Submitted'), ('approved', 'Approved'), ('in_progress', 'In Progress'), ('completed', 'Completed'), ('reviewed', 'Reviewed'), ('finalised', 'Finalised')], default='draft', max_length=20),
        ),
        migrations.AlterField(
            model_name='goalsheet',
            name='target_value',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='goalsheet',
            name='weight',
            field=models.IntegerField(blank=True, default=10, null=True),
        ),
        migrations.AlterField(
            model_name='promotionrecommendation',
            name='status',
            field=models.CharField(choices=[('recommended', 'Recommended'), ('approved', 'Approved'), ('rejected', 'Rejected'), ('implemented', 'Implemented'), ('declined', 'Declined')], default='recommended', max_length=20),
        ),
    ]
