# Generated by Django 6.0.5 on 2026-05-27 10:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_user_reset_token_user_reset_token_expires_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('employee', 'Employee'), ('manager', 'Manager'), ('hr', 'HR (Human Resources)'), ('recruiter', 'Recruiter'), ('payroll', 'Payroll Executive'), ('admin', 'Admin')], default='employee', max_length=20),
        ),
    ]
