# Generated by Django 6.0.5 on 2026-05-29 12:14

import core.utils
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_alter_user_employee_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='employee_id',
            field=models.CharField(default=core.utils.generate_employee_id, max_length=50, unique=True),
        ),
    ]
